
services:
  dongguatv:
    build: .
    container_name: dongguatv
    restart: unless-stopped
    ports:
    - "3000:3000"
    environment:
    #- PORT=3000
    - TMDB_API_KEY=key
    - ADMIN_PASSWORD=admin